In [42]:
import pandas as pd
df = pd.read_html('http://www.espn.com/nba/team/schedule/_/name/bos')

In [43]:
s = df[0]
s.head()

,0,1,2,3,4,5,6
0,2018 Regular Season Schedule,NaN,NaN,NaN,NaN,NaN,NaN
1,OCTOBER,OPPONENT,RESULT,W-L,HI POINTS,HI REBOUNDS,HI ASSISTS
2,"Tue, Oct 17",@Cleveland,L102-99,0-1,L. James 29,L. James 16,K. Irving 10
3,"Wed, Oct 18",vsMilwaukee,L108-100,0-2,G. Antetokounmpo 37,G. Antetokounmpo 13,K. Middleton 6
4,"Fri, Oct 20",@Philadelphia,W102-92,1-2,K. Irving 21,J. Embiid 14,B. Simmons 5

In [5]:
df{:,1}

SyntaxError: invalid syntax (<ipython-input-5-d599240711c7>, line 1)

In [9]:
df[0:1]

[                               0                1            2      3  \
 0   2018 Regular Season Schedule              NaN          NaN    NaN
 1                        OCTOBER         OPPONENT       RESULT    W-L
 2                    Tue, Oct 17       @Cleveland      L102-99    0-1
 3                    Wed, Oct 18      vsMilwaukee     L108-100    0-2
 4                    Fri, Oct 20    @Philadelphia      W102-92    1-2
 5                    Tue, Oct 24      vsNY Knicks      W110-89    2-2
 6                    Thu, Oct 26       @Milwaukee       W96-89    3-2
 7                    Sat, Oct 28           @Miami       W96-90    4-2
 8                    Mon, Oct 30    vsSan Antonio      W108-94    5-2
 9                       NOVEMBER         OPPONENT       RESULT    W-L
 10                    Wed, Nov 1     vsSacramento      W113-86    6-2
 11                    Fri, Nov 3   @Oklahoma City      W101-94    7-2
 12                    Sun, Nov 5         @Orlando      W104-88    8-2
 13                    Mon, Nov 6         @Atlanta     W110-107    9-2
 14                    Wed, Nov 8    vsLos Angeles      W107-96   10-2
 15                   Fri, Nov 10      vsCharlotte       W90-87   11-2
 16                   Sun, Nov 12        vsToronto       W95-94   12-2
 17                   Tue, Nov 14        @Brooklyn     W109-102   13-2
 18                   Thu, Nov 16   vsGolden State       W92-88   14-2
 19                   Sat, Nov 18         @Atlanta      W110-99   15-2
 20                   Mon, Nov 20          @Dallas  W110-102 OT   16-2
 21                   Wed, Nov 22           @Miami      L104-98   16-3
 22                   Fri, Nov 24        vsOrlando     W118-103   17-3
 23                   Sat, Nov 25         @Indiana      W108-98   18-3
 24                   Mon, Nov 27        vsDetroit     L118-108   18-4
 25                   Thu, Nov 30   vsPhiladelphia      W108-97   19-4
 26                      DECEMBER         OPPONENT       RESULT    W-L
 27                    Sat, Dec 2        vsPhoenix     W116-111   20-4
 28                    Mon, Dec 4      vsMilwaukee     W111-100   21-4
 29                    Wed, Dec 6         vsDallas       W97-90   22-4
 ..                           ...              ...          ...    ...
 61                    Tue, Feb 6         @Toronto      7:30 PM    NaN
 62                    Thu, Feb 8      @Washington      8:00 PM    TNT
 63                    Fri, Feb 9        vsIndiana      7:30 PM    NaN
 64                   Sun, Feb 11      vsCleveland      3:30 PM    NaN
 65                   Wed, Feb 14             vsLA      8:00 PM    NaN
 66                   Fri, Feb 23         @Detroit      7:00 PM    NaN
 67                   Sat, Feb 24       @NY Knicks      7:30 PM    NaN
 68                   Mon, Feb 26        vsMemphis      7:30 PM    NaN
 69                   Wed, Feb 28      vsCharlotte      7:30 PM    NaN
 70                         MARCH         OPPONENT    TIME (ET)     TV
 71                    Sat, Mar 3         @Houston      8:30 PM    NaN
 72                    Mon, Mar 5         @Chicago      8:00 PM    NaN
 73                    Thu, Mar 8       @Minnesota      8:00 PM    TNT
 74                   Sun, Mar 11        vsIndiana      7:30 PM    NaN
 75                   Wed, Mar 14     vsWashington      8:00 PM    NaN
 76                   Fri, Mar 16         @Orlando      7:00 PM    NaN
 77                   Sun, Mar 18     @New Orleans      6:00 PM    NaN
 78                   Tue, Mar 20  vsOklahoma City      8:00 PM    TNT
 79                   Fri, Mar 23        @Portland     10:00 PM  NBATV
 80                   Sun, Mar 25      @Sacramento      6:00 PM    NaN
 81                   Mon, Mar 26         @Phoenix     10:00 PM  NBATV
 82                   Wed, Mar 28            @Utah      9:30 PM    NaN
 83                   Sat, Mar 31        vsToronto      7:30 PM  NBATV
 84                         APRIL         OPPONENT    TIME (ET)     TV
 85                    Tue, Apr 3       @Milwaukee      8:00 PM    NaN
 86                    Wed, Apr 4         @Toronto      7:00 PM    NaN
 87                    Fri, Apr 6        vsChicago      7:30 PM    NaN
 88                    Sun, Apr 8        vsAtlanta      1:00 PM    NaN
 89                   Tue, Apr 10      @Washington      8:00 PM    TNT
 90                   Wed, Apr 11       vsBrooklyn      8:00 PM    NaN

                             4                    5                6
 0                         NaN                  NaN              NaN
 1                   HI POINTS          HI REBOUNDS       HI ASSISTS
 2                 L. James 29          L. James 16     K. Irving 10
 3         G. Antetokounmpo 37  G. Antetokounmpo 13   K. Middleton 6
 4                K. Irving 21         J. Embiid 14     B. Simmons 5
 5                 J. Brown 23         E. Kanter 19    R. Sessions 7
 6         G. Antetokounmpo 28  G. Antetokounmpo 10      K. Irving 7
 7                K. Irving 24        J. Winslow 12      G. Dragic 4
 8                K. Irving 24        A. Horford 13       M. Smart 7
 9                   HI POINTS          HI REBOUNDS       HI ASSISTS
 10               K. Irving 22          D. Theis 10       M. Smart 8
 11               P. George 25        C. Anthony 14  R. Westbrook 11
 12               A. Gordon 18         A. Gordon 12       M. Smart 8
 13               K. Irving 35         D. Dedmon 12     A. Horford 9
 14               A. Baynes 21         J. Randle 12       M. Smart 6
 15               K. Walker 20          J. Brown 13     K. Walker 11
 16              D. DeRozan 24           D. Theis 8       M. Smart 9
 17               K. Irving 25        A. Horford 11  S. Dinwiddie 11
 18               K. Durant 24        A. Horford 11      K. Irving 6
 19               K. Irving 30          D. Dedmon 8    D. Schroder 9
 20               K. Irving 47       D. Nowitzki 12       M. Smart 8
 21               G. Dragic 27      H. Whiteside 10     D. Waiters 6
 22               K. Irving 30        N. Vucevic 11    A. Horford 10
 23               K. Irving 25      L. Stephenson 8     A. Horford 6
 24               T. Harris 31       A. Drummond 22      K. Irving 9
 25               K. Irving 36          D. Saric 10       M. Smart 8
 26                  HI POINTS          HI REBOUNDS       HI ASSISTS
 27               D. Booker 38       T. Chandler 18    A. Horford 11
 28        G. Antetokounmpo 40         A. Horford 9     A. Horford 8
 29               K. Irving 23          D. Theis 11     A. Horford 8
 ..                        ...                  ...              ...
 61     943 available from $55                  NaN              NaN
 62   2,093 available from $50                  NaN              NaN
 63   1,649 available from $73                  NaN              NaN
 64    881 available from $335                  NaN              NaN
 65   2,552 available from $51                  NaN              NaN
 66   2,261 available from $30                  NaN              NaN
 67  1,685 available from $169                  NaN              NaN
 68   2,317 available from $28                  NaN              NaN
 69   2,324 available from $44                  NaN              NaN
 70                    TICKETS                  NaN              NaN
 71   1,787 available from $69                  NaN              NaN
 72   2,483 available from $28                  NaN              NaN
 73     603 available from $32                  NaN              NaN
 74   1,825 available from $59                  NaN              NaN
 75   2,478 available from $56                  NaN              NaN
 76   1,513 available from $28                  NaN              NaN
 77   1,932 available from $19                  NaN              NaN
 78   2,225 available from $85                  NaN              NaN
 79   1,247 available from $43                  NaN              NaN
 80     847 available from $39                  NaN              NaN
 81   1,203 available from $26                  NaN              NaN
 82   1,252 available from $34                  NaN              NaN
 83  1,720 available from $105                  NaN              NaN
 84                    TICKETS                  NaN              NaN
 85   2,097 available from $18                  NaN              NaN
 86   1,758 available from $50                  NaN              NaN
 87   2,355 available from $74                  NaN              NaN
 88   3,055 available from $36                  NaN              NaN
 89   2,746 available from $21                  NaN              NaN
 90   3,124 available from $39                  NaN              NaN

 [91 rows x 7 columns]]

In [15]:
df[0].columns =['A','B','C','D','E','F','G']

In [46]:

s.head()
s.columns = ['Date','Location','Results','W/L','Top Scorer','Top Rebounder','Top Assist']
s.head()

,Date,Location,Results,W/L,Top Scorer,Top Rebounder,Top Assist
0,2018 Regular Season Schedule,NaN,NaN,NaN,NaN,NaN,NaN
1,OCTOBER,OPPONENT,RESULT,W-L,HI POINTS,HI REBOUNDS,HI ASSISTS
2,"Tue, Oct 17",@Cleveland,L102-99,0-1,L. James 29,L. James 16,K. Irving 10
3,"Wed, Oct 18",vsMilwaukee,L108-100,0-2,G. Antetokounmpo 37,G. Antetokounmpo 13,K. Middleton 6
4,"Fri, Oct 20",@Philadelphia,W102-92,1-2,K. Irving 21,J. Embiid 14,B. Simmons 5

In [52]:
s['Results']= s['Results'].str.split('-', expand = True)

In [53]:
s

,Date,Location,Results,W/L,Top Scorer,Top Rebounder,Top Assist
0,2018 Regular Season Schedule,NaN,NaN,NaN,NaN,NaN,NaN
1,OCTOBER,OPPONENT,RESULT,W-L,HI POINTS,HI REBOUNDS,HI ASSISTS
2,"Tue, Oct 17",@Cleveland,L102,0-1,L. James 29,L. James 16,K. Irving 10
3,"Wed, Oct 18",vsMilwaukee,L108,0-2,G. Antetokounmpo 37,G. Antetokounmpo 13,K. Middleton 6
4,"Fri, Oct 20",@Philadelphia,W102,1-2,K. Irving 21,J. Embiid 14,B. Simmons 5
5,"Tue, Oct 24",vsNY Knicks,W110,2-2,J. Brown 23,E. Kanter 19,R. Sessions 7
6,"Thu, Oct 26",@Milwaukee,W96,3-2,G. Antetokounmpo 28,G. Antetokounmpo 10,K. Irving 7
7,"Sat, Oct 28",@Miami,W96,4-2,K. Irving 24,J. Winslow 12,G. Dragic 4
8,"Mon, Oct 30",vsSan Antonio,W108,5-2,K. Irving 24,A. Horford 13,M. Smart 7
9,NOVEMBER,OPPONENT,RESULT,W-L,HI POINTS,HI REBOUNDS,HI ASSISTS
10,"Wed, Nov 1",vsSacramento,W113,6-2,K. Irving 22,D. Theis 10,M. Smart 8
11,"Fri, Nov 3",@Oklahoma City,W101,7-2,P. George 25,C. Anthony 14,R. Westbrook 11
12,"Sun, Nov 5",@Orlando,W104,8-2,A. Gordon 18,A. Gordon 12,M. Smart 8
13,"Mon, Nov 6",@Atlanta,W110,9-2,K. Irving 35,D. Dedmon 12,A. Horford 9
14,"Wed, Nov 8",vsLos Angeles,W107,10-2,A. Baynes 21,J. Randle 12,M. Smart 6
15,"Fri, Nov 10",vsCharlotte,W90,11-2,K. Walker 20,J. Brown 13,K. Walker 11
16,"Sun, Nov 12",vsToronto,W95,12-2,D. DeRozan 24,D. Theis 8,M. Smart 9
17,"Tue, Nov 14",@Brooklyn,W109,13-2,K. Irving 25,A. Horford 11,S. Dinwiddie 11
18,"Thu, Nov 16",vsGolden State,W92,14-2,K. Durant 24,A. Horford 11,K. Irving 6
19,"Sat, Nov 18",@Atlanta,W110,15-2,K. Irving 30,D. Dedmon 8,D. Schroder 9
20,"Mon, Nov 20",@Dallas,W110,16-2,K. Irving 47,D. Nowitzki 12,M. Smart 8
21,"Wed, Nov 22",@Miami,L104,16-3,G. Dragic 27,H. Whiteside 10,D. Waiters 6
22,"Fri, Nov 24",vsOrlando,W118,17-3,K. Irving 30,N. Vucevic 11,A. Horford 10
23,"Sat, Nov 25",@Indiana,W108,18-3,K. Irving 25,L. Stephenson 8,A. Horford 6
24,"Mon, Nov 27",vsDetroit,L118,18-4,T. Harris 31,A. Drummond 22,K. Irving 9
25,"Thu, Nov 30",vsPhiladelphia,W108,19-4,K. Irving 36,D. Saric 10,M. Smart 8
26,DECEMBER,OPPONENT,RESULT,W-L,HI POINTS,HI REBOUNDS,HI ASSISTS
27,"Sat, Dec 2",vsPhoenix,W116,20-4,D. Booker 38,T. Chandler 18,A. Horford 11
28,"Mon, Dec 4",vsMilwaukee,W111,21-4,G. Antetokounmpo 40,A. Horford 9,A. Horford 8
29,"Wed, Dec 6",vsDallas,W97,22-4,K. Irving 23,D. Theis 11,A. Horford 8
...,...,...,...,...,...,...,...
61,"Tue, Feb 6",@Toronto,7:30 PM,NaN,943 available from $55,NaN,NaN
62,"Thu, Feb 8",@Washington,8:00 PM,TNT,"2,089 available from $50",NaN,NaN
63,"Fri, Feb 9",vsIndiana,7:30 PM,NaN,"1,645 available from $73",NaN,NaN
64,"Sun, Feb 11",vsCleveland,3:30 PM,NaN,881 available from $335,NaN,NaN
65,"Wed, Feb 14",vsLA,8:00 PM,NaN,"2,552 available from $51",NaN,NaN
66,"Fri, Feb 23",@Detroit,7:00 PM,NaN,"2,281 available from $30",NaN,NaN
67,"Sat, Feb 24",@NY Knicks,7:30 PM,NaN,"1,714 available from $169",NaN,NaN
68,"Mon, Feb 26",vsMemphis,7:30 PM,NaN,"2,313 available from $28",NaN,NaN
69,"Wed, Feb 28",vsCharlotte,7:30 PM,NaN,"2,320 available from $44",NaN,NaN
70,MARCH,OPPONENT,TIME (ET),TV,TICKETS,NaN,NaN
71,"Sat, Mar 3",@Houston,8:30 PM,NaN,"1,787 available from $69",NaN,NaN
72,"Mon, Mar 5",@Chicago,8:00 PM,NaN,"2,483 available from $28",NaN,NaN
73,"Thu, Mar 8",@Minnesota,8:00 PM,TNT,603 available from $32,NaN,NaN
74,"Sun, Mar 11",vsIndiana,7:30 PM,NaN,"1,831 available from $59",NaN,NaN
75,"Wed, Mar 14",vsWashington,8:00 PM,NaN,"2,478 available from $56",NaN,NaN
76,"Fri, Mar 16",@Orlando,7:00 PM,NaN,"1,515 available from $28",NaN,NaN
77,"Sun, Mar 18",@New Orleans,6:00 PM,NaN,"1,932 available from $19",NaN,NaN
78,"Tue, Mar 20",vsOklahoma City,8:00 PM,TNT,"2,225 available from $85",NaN,NaN
79,"Fri, Mar 23",@Portland,10:00 PM,NBATV,"1,246 available from $43",NaN,NaN
80,"Sun, Mar 25",@Sacramento,6:00 PM,NaN,847 available from $39,NaN,NaN
81,"Mon, Mar 26",@Phoenix,10:00 PM,NBATV,"1,203 available from $26",NaN,NaN
82,"Wed, Mar 28",@Utah,9:30 PM,NaN,"1,252 available from $34",NaN,NaN
83,"Sat, Mar 31",vsToronto,7:30 PM,NBATV,"1,703 available from $105",NaN,NaN
84,APRIL,OPPONENT,TIME (ET),TV,TICKETS,NaN,NaN
85,"Tue, Apr 3",@Milwaukee,8:00 PM,NaN,"2,097 available from $18",NaN,NaN
86,"Wed, Apr 4",@Toronto,7:00 PM,NaN,"1,758 available from $50",NaN,NaN
87,"Fri, Apr 6",vsChicago,7:30 PM,NaN,"2,351 available from $74",NaN,NaN
88,"Sun, Apr 8",vsAtlanta,1:00 PM,NaN,"3,055 available from $36",NaN,NaN
89,"Tue, Apr 10",@Washington,8:00 PM,TNT,"2,746 available from $21",NaN,NaN
90,"Wed, Apr 11",vsBrooklyn,8:00 PM,NaN,"3,124 available from $39",NaN,NaN